image: node:9.1.0
services:
    - postgres:10.0

cache:
    untracked: true

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres


stages:
    - build
    - test

install:
    stage: build
    script:
        - npm install --global yarn
        - yarn

mocha:
    stage: test
    script:
        - yarn test:routes:index

lint:
    stage: test
    script:
        - yarn run _gl-lint
