image: node:9.1.0

cache:
    untracked: true

stages:
    - build
    - test
    - lint

install:
    stage: build
    script:
        - npm install --global yarn
        - yarn

unit-test:
    stage: test
    script:
        - yarn test:unit

route-test:
    stage: test
    script:
        - yarn test:routes

lint:
    stage: lint
    script:
        - yarn _lint
