image: node:9.1.0

cache:
    untracked: true

stages:
    - build
    - test

install:
    stage: build
    script:
        - npm install --global yarn
        - yarn

mocha:
    stage: test
    script:
        - yarn test:routes:index

lint:
    stage: test
    script:
        - yarn run _gl-lint
