image: node:9.1.0
services:
  - postgres:10.0
cache:
  untracked: true

stages:
  - build
  - test

install:
  stage: build
  script:
    - npm install

mocha:
  stage: test
  script:
    - npm test

lint:
  stage: test
  script:
    - npm run _gl-lint
