import requests

token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsidXNlcm5hbWUiOiJoYWZlZXoiLCJwYXNzd29yZEludGVybmFsIjpudWxsLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA0LTI2VDAxOjUwOjIzLjEwOVoiLCJ1cGRhdGVkQXQiOiIyMDE4LTA0LTI2VDAxOjUwOjIzLjEwOVoiLCJ1c2VyR3JvdXBzIjpbeyJpZCI6MSwibmFtZSI6ImxvZ2dpbmciLCJjYW5DcmVhdGVVc2VycyI6bnVsbCwiY2FuRGVsZXRlVXNlcnMiOm51bGwsImNhbkVkaXRVc2VycyI6bnVsbCwiY2FuQ3JlYXRlUHJvamVjdHMiOm51bGwsImNhbkRlbGV0ZVByb2plY3RzIjpudWxsLCJjYW5FZGl0UHJvamVjdHMiOm51bGwsImNhbkFjY2Vzc0xvZ3MiOnRydWUsImlzSW50ZXJuYWwiOmZhbHNlLCJkZXNjcmlwdGlvbiI6IkFsbG93cyBQb3N0IHRvIExvZyIsIlVzZXJIYXNQcml2aWxlZ2UiOnsidXNlcm5hbWUiOiJoYWZlZXoiLCJwcml2aWxlZ2VJZCI6MX19LHsiaWQiOjIsIm5hbWUiOiJhZG1pbiIsImNhbkNyZWF0ZVVzZXJzIjp0cnVlLCJjYW5EZWxldGVVc2VycyI6dHJ1ZSwiY2FuRWRpdFVzZXJzIjp0cnVlLCJjYW5DcmVhdGVQcm9qZWN0cyI6dHJ1ZSwiY2FuRGVsZXRlUHJvamVjdHMiOnRydWUsImNhbkVkaXRQcm9qZWN0cyI6dHJ1ZSwiY2FuQWNjZXNzTG9ncyI6bnVsbCwiaXNJbnRlcm5hbCI6ZmFsc2UsImRlc2NyaXB0aW9uIjoiU3lzdGVtcyBhZG1pbiIsIlVzZXJIYXNQcml2aWxlZ2UiOnsidXNlcm5hbWUiOiJoYWZlZXoiLCJwcml2aWxlZ2VJZCI6Mn19XSwicHJvamVjdHMiOlt7Im5hbWUiOiJmYWtlLXByb2plY3QiLCJyb290Rm9sZGVySWQiOiJmNTYzYzQxNC01MzFlLTRmZjctODFiOC1hNGZlM2Y3NTM5ZmYiLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA0LTI2VDAzOjMzOjIzLjI1N1oiLCJsYXN0QWN0aXZpdHkiOiIyMDE4LTA0LTI2VDAzOjMzOjIzLjI1N1oiLCJVc2VySm9pbnNQcm9qZWN0Ijp7InVzZXJuYW1lIjoiaGFmZWV6IiwicHJvamVjdE5hbWUiOiJmYWtlLXByb2plY3QiLCJjb250cmlidXRvckdyb3VwTmFtZSI6InByb2plY3RPd25lciIsImpvaW5EYXRlIjoiMjAxOC0wNC0yNlQwMzozMzoyMy4yNzdaIiwidXBkYXRlZEF0IjoiMjAxOC0wNC0yNlQwMzozMzoyMy4yNzdaIiwiY29udHJpYnV0b3JHcm91cElkIjpudWxsfX0seyJuYW1lIjoicmVmc2ciLCJyb290Rm9sZGVySWQiOiIzZWRmN2E0Ny1jOTFlLTQ1MmItYjc5Ni01MzcxOThlNmEyYzEiLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA0LTI2VDAyOjEwOjE3LjM4MVoiLCJsYXN0QWN0aXZpdHkiOiIyMDE4LTA0LTI2VDAyOjEwOjE3LjM4MVoiLCJVc2VySm9pbnNQcm9qZWN0Ijp7InVzZXJuYW1lIjoiaGFmZWV6IiwicHJvamVjdE5hbWUiOiJyZWZzZyIsImNvbnRyaWJ1dG9yR3JvdXBOYW1lIjoicHJvamVjdE93bmVyIiwiam9pbkRhdGUiOiIyMDE4LTA0LTI2VDAyOjEwOjE3LjM5MloiLCJ1cGRhdGVkQXQiOiIyMDE4LTA0LTI2VDAyOjEwOjE3LjM5MloiLCJjb250cmlidXRvckdyb3VwSWQiOm51bGx9fSx7Im5hbWUiOiJ0b210b20iLCJyb290Rm9sZGVySWQiOiJmNWYzMjkzOC02MWUxLTRkMDYtOTljMy05ZDY5YjJkZjBiNzAiLCJjcmVhdGlvbkRhdGUiOiIyMDE4LTA0LTI2VDAxOjUzOjIwLjMzMloiLCJsYXN0QWN0aXZpdHkiOiIyMDE4LTA0LTI2VDAxOjUzOjIwLjMzMloiLCJVc2VySm9pbnNQcm9qZWN0Ijp7InVzZXJuYW1lIjoiaGFmZWV6IiwicHJvamVjdE5hbWUiOiJ0b210b20iLCJjb250cmlidXRvckdyb3VwTmFtZSI6InByb2plY3RPd25lciIsImpvaW5EYXRlIjoiMjAxOC0wNC0yNlQwMTo1MzoyMC4zNDBaIiwidXBkYXRlZEF0IjoiMjAxOC0wNC0yNlQwMTo1MzoyMC4zNDBaIiwiY29udHJpYnV0b3JHcm91cElkIjpudWxsfX1dfSwiaWF0IjoxNTI0NzEzOTAzLCJleHAiOjE1MjQ3MzU1MDN9.E9yz7zEbQgM1AFfRB0roYnPFS5aj3ZwPHJ4uqloMRrE"
chunksize = 1024 * 4;


def read_in_chunks(file_object):
	"""Lazy function (generator) to read a file piece by piece.
	Default chunk size: 1k."""
	while True:
		data = file_object.read(chunksize)
		if not data:
			break
		yield data


f = open('/cs/scratch/cjd24/0701.czi')
if __name__ == "__main__":
	iterator = read_in_chunks(f)

	r = requests.post("http://localhost:3000/cs3099group-be-4/projects/fake-project/files/0701.czi", headers={"authorization":token}, data=iterator.next())

	print(r.text)

	offset = chunksize;
	current = iterator.next()
	while(True):
		nchunk = iterator.next()
		if not nchunk:
			r = requests.post("http://localhost:3000/cs3099group-be-4/projects/fake-project/files/0701.czi?overwrite=true&offset=" + str(offset) + "&final=true", headers={"authorization":token}, data=current)
			print(r.text)
			break;

		r = requests.post("http://localhost:3000/cs3099group-be-4/projects/fake-project/files/0701.czi?overwrite=true&offset=" + str(offset), headers={"authorization":token}, data=current)
		print(r.text)
		current = nchunk;
		offset += chunksize
